### ISSUE TITLE
Undefined method 'data'

### ISSUE THREAD

**Issue by hashrocketeer** [renz45/mandrill_mailer#97] opened 2015-10-01 17:52 UTC
![screen shot 2015-10-01 at 1 51 08 pm](https://cloud.githubusercontent.com/assets/317960/10228964/968ec370-6843-11e5-8f5d-d4bd7b7c83ae.png)

Is this a mandrill-mailer issue?

**Comment by renz45** [comment] 2015-10-01 18:15
Hard to say without seeing the mailer code. :) I haven't seen any other reports of similar issues so I lean towards there being something else wrong.

**Comment by olivierlacan** [comment] 2015-10-01 18:26
@renz45 @hashrocketeer :arrow_right: https://github.com/orientation/orientation/blob/master/app/mailers/article_mailer.rb#L9-L23

**Comment by renz45** [comment] 2015-10-01 18:31
Oh hah its for orientation, I guess I didn't look that close at the stack trace D: Sorry about that.

Maybe its the older version of the mailer that orientation uses?

**Comment by olivierlacan** [comment] 2015-10-01 18:56
Yep, we just use `data` and that's deprecated in 1.0.0. This is not a bug. Closing. :-)

**Closed by olivierlacan** 2015-10-01 18:56 UTC
