### ISSUE TITLE
assets precompile error

### ISSUE THREAD

**Issue by lvalenzuela** [renz45/mandrill_mailer#119] opened 2016-05-24 22:49 UTC
Hi,
I'm getting the following error when trying to precompile assets.

```bash
bundle exec rake assets:precompile --trace
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'mandrill_mailer'.
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/<user>/Documents/Clientes/Achuntale/Proyectos/apuntale-dev/config/application.rb:7:in `<top (required)>'
/home/<user>/Documents/Clientes/Achuntale/Proyectos/apuntale-dev/Rakefile:4:in `require'
/home/<user>/Documents/Clientes/Achuntale/Proyectos/apuntale-dev/Rakefile:4:in `<top (required)>'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:94:in `block in load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:93:in `load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:77:in `block in run'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/rake:23:in `load'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/rake:23:in `<main>'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
ArgumentError: wrong number of arguments (0 for 1)
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activejob-0/lib/active_job/queue_name.rb:6:in `queue_as'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/mandrill_mailer-1.4.0/lib/mandrill_mailer/mandrill_template_later.rb:4:in `<class:MandrillTemplateJob>'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/mandrill_mailer-1.4.0/lib/mandrill_mailer/mandrill_template_later.rb:3:in `<module:MandrillMailer>'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/mandrill_mailer-1.4.0/lib/mandrill_mailer/mandrill_template_later.rb:2:in `<top (required)>'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/mandrill_mailer-1.4.0/lib/mandrill_mailer/template_mailer.rb:109:in `<top (required)>'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/mandrill_mailer-1.4.0/lib/mandrill_mailer.rb:5:in `<top (required)>'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/<user>/Documents/Clientes/Achuntale/Proyectos/apuntale-dev/config/application.rb:7:in `<top (required)>'
/home/<user>/Documents/Clientes/Achuntale/Proyectos/apuntale-dev/Rakefile:4:in `require'
/home/<user>/Documents/Clientes/Achuntale/Proyectos/apuntale-dev/Rakefile:4:in `<top (required)>'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:94:in `block in load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:93:in `load_rakefile'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:77:in `block in run'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/home/<user>/.rvm/gems/ruby-2.1.4/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/rake:23:in `load'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/rake:23:in `<main>'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/home/<user>/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

My current mail.rb has the following configuration

```
MandrillMailer.configure do |config|
  config.api_key = ENV['MANDRILL_API_KEY'],
  config.deliver_later_queue_name = :default
end
```

**Comment by renz45** [comment] 2016-05-25 14:03
This doesn't really look related to anything within the gem. Can you post your gemfile and gemfile.lock?

**Comment by lvalenzuela** [comment] 2016-05-25 14:26
Gemfile

```
source 'https://rubygems.org'

ruby "2.1.4"
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.7'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-easing-rails'
gem 'jquery-slimscroll-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'sprockets-rails'
# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'chronic'
gem 'paperclip'
gem 'gon'
gem 'aws-sdk'
gem 'rails_admin'
gem 'simple_form'
gem 'cancancan', '~> 1.9'
gem 'ckeditor', github: 'mendi/ckeditor'
gem 'awesome_print', '1.6.1', group: :development
gem 'pry-rails', '0.3.2', group: :development
gem 'gretel', '3.0.8'
gem 'pg_search', '0.7.8'
gem "highcharts-rails", "~> 3.0.0"
gem 'mini_magick'
gem 'fog'
gem 'carrierwave'
gem 'rails-jquery-autocomplete'
gem 'quiet_assets'
gem 'mandrill_mailer'
gem 'mediaelement_rails'
gem 'will_paginate-bootstrap'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'jspdf-rails'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
group :development do
    gem 'capistrano',         require: false
    gem 'capistrano-rvm',     require: false
    gem 'capistrano-rails',   require: false
    gem 'capistrano-bundler', require: false
    gem 'capistrano3-puma',   require: false
end

gem 'puma'

# Use debugger
# gem 'debugger', group: [:development, :test]
```

gemfile.lock

```
GIT
  remote: git://github.com/mendi/ckeditor.git
  revision: ab83fc9be1203ac64dc13d552c754c2765cc659c
  specs:
    ckeditor (4.1.1)
      cocaine
      orm_adapter (~> 0.5.0)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.2)
    actionmailer (4.1.7)
      actionpack (= 4.1.7)
      actionview (= 4.1.7)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.7)
      actionview (= 4.1.7)
      activesupport (= 4.1.7)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.7)
      activesupport (= 4.1.7)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    activejob (0)
      activemodel-globalid
      activesupport (>= 4.1.0)
    activemodel (4.1.7)
      activesupport (= 4.1.7)
      builder (~> 3.1)
    activemodel-globalid (0.1.1)
      activemodel (>= 4.1.0)
      activesupport (>= 4.1.0)
    activerecord (4.1.7)
      activemodel (= 4.1.7)
      activesupport (= 4.1.7)
      arel (~> 5.0.0)
    activesupport (4.1.7)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    airbrussh (1.0.2)
      sshkit (>= 1.6.1, != 1.7.0)
    arel (5.0.1.20140414130214)
    autoprefixer-rails (6.3.6.1)
      execjs
    awesome_print (1.6.1)
    aws-sdk (2.3.7)
      aws-sdk-resources (= 2.3.7)
    aws-sdk-core (2.3.7)
      jmespath (~> 1.0)
    aws-sdk-resources (2.3.7)
      aws-sdk-core (= 2.3.7)
    bcrypt (3.1.11)
    bootstrap-sass (3.3.5)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    builder (3.2.2)
    cancancan (1.14.0)
    capistrano (3.5.0)
      airbrussh (>= 1.0.0)
      capistrano-harrow
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-harrow (0.5.1)
    capistrano-rails (1.1.6)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano3-puma (1.2.1)
      capistrano (~> 3.0)
      puma (>= 2.6)
    carrierwave (0.11.2)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
      mimemagic (>= 0.3.0)
    chronic (0.10.2)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.1)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    devise (4.1.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.1)
      responders
      warden (~> 1.2.3)
    erubis (2.7.0)
    excon (0.49.0)
    execjs (2.7.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.38.0)
      fog-aliyun (>= 0.1.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-cloudatcost (~> 0.1.0)
      fog-core (~> 1.32)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (<= 0.1.0)
      fog-json
      fog-local
      fog-openstack
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-rackspace
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-vsphere (>= 0.4.0)
      fog-xenserver
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
    fog-aliyun (0.1.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      ipaddress (~> 0.8)
      xml-simple (~> 1.1)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.9.2)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.10.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-cloudatcost (0.1.2)
      fog-core (~> 1.36)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.40.0)
      builder
      excon (~> 0.49)
      formatador (~> 0.2)
    fog-dynect (0.0.3)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.3.0)
      fog-core (~> 1.27)
    fog-openstack (0.1.6)
      fog-core (>= 1.39)
      fog-json (>= 1.0)
      ipaddress (>= 0.8)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.5)
      fog-core
      fog-xml
      nokogiri
    fog-rackspace (0.1.1)
      fog-core (>= 1.35)
      fog-json (>= 1.0)
      fog-xml (>= 0.1)
      ipaddress (>= 0.8)
    fog-radosgw (0.0.5)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.7.5)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (1.1.1)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-vsphere (0.7.0)
      fog-core
      rbvmomi (~> 1.8)
    fog-xenserver (0.2.3)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-rails (4.6.3.0)
      railties (>= 3.2, < 5.1)
    formatador (0.2.5)
    gon (6.0.1)
      actionpack (>= 3.0)
      json
      multi_json
      request_store (>= 1.0)
    gretel (3.0.8)
      rails (>= 3.2.0)
    haml (4.0.7)
      tilt
    hashie (3.4.4)
    highcharts-rails (3.0.10)
      railties (>= 3.1)
    hike (1.2.3)
    i18n (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.3)
    jbuilder (2.4.1)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    jmespath (1.2.4)
      json_pure (>= 1.8.1)
    jquery-easing-rails (0.0.2)
      railties (>= 3.1.0)
    jquery-rails (3.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-slimscroll-rails (1.0.9)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    json_pure (1.8.3)
    jspdf-rails (1.0.3)
      jquery-rails
      rails (>= 3.1.0)
    jwt (1.5.1)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    mandrill-api (1.0.53)
      excon (>= 0.16.0, < 1.0)
      json (>= 1.7.7, < 2.0)
    mandrill_mailer (1.4.0)
      actionpack
      activejob
      activesupport
      mandrill-api (~> 1.0.9)
    mediaelement_rails (0.8.2)
      jquery-rails (>= 1.0)
      railties (>= 3.1)
    method_source (0.8.2)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0221)
    mimemagic (0.3.0)
    mini_magick (4.5.1)
    mini_portile2 (2.0.0)
    minitest (5.9.0)
    multi_json (1.12.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nested_form (0.3.2)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.1.1)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    oauth (0.5.1)
    oauth2 (1.1.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0, < 1.5.2)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.3.1)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-facebook (3.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth (1.1.0)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-twitter (1.2.1)
      json (~> 1.3)
      omniauth-oauth (~> 1.1)
    orm_adapter (0.5.0)
    paperclip (4.3.6)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    pg (0.18.4)
    pg_search (0.7.8)
      activerecord (>= 3.1)
      activesupport (>= 3.1)
      arel
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-rails (0.3.2)
      pry (>= 0.9.10)
    puma (3.4.0)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.5.5)
    rack-pjax (0.8.0)
      nokogiri (~> 1.5)
      rack (~> 1.1)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.1.7)
      actionmailer (= 4.1.7)
      actionpack (= 4.1.7)
      actionview (= 4.1.7)
      activemodel (= 4.1.7)
      activerecord (= 4.1.7)
      activesupport (= 4.1.7)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.7)
      sprockets-rails (~> 2.0)
    rails-jquery-autocomplete (1.0.3)
      rails (>= 3.2)
    rails_admin (0.8.1)
      builder (~> 3.1)
      coffee-rails (~> 4.0)
      font-awesome-rails (>= 3.0, < 5)
      haml (~> 4.0)
      jquery-rails (>= 3.0, < 5)
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.14)
      nested_form (~> 0.3)
      rack-pjax (~> 0.7)
      rails (~> 4.0)
      remotipart (~> 1.0)
      safe_yaml (~> 1.0)
      sass-rails (>= 4.0, < 6)
    railties (4.1.7)
      actionpack (= 4.1.7)
      activesupport (= 4.1.7)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (11.1.2)
    rbvmomi (1.8.2)
      builder
      nokogiri (>= 1.4.1)
      trollop
    rdoc (4.2.2)
      json (~> 1.4)
    remotipart (1.2.1)
    request_store (1.3.1)
    responders (1.1.2)
      railties (>= 3.2, < 4.2)
    safe_yaml (1.0.4)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    simple_form (3.2.1)
      actionpack (> 4, < 5.1)
      activemodel (> 4, < 5.1)
    slop (3.6.0)
    spring (1.7.1)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sshkit (1.10.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    trollop (2.1.2)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.0)
      execjs (>= 0.3.0, < 3)
    warden (1.2.6)
      rack (>= 1.0)
    wicked_pdf (1.0.6)
    will_paginate (3.1.0)
    will_paginate-bootstrap (1.0.1)
      will_paginate (>= 3.0.3)
    wkhtmltopdf-binary (0.9.9.3)
    xml-simple (1.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  autoprefixer-rails
  awesome_print (= 1.6.1)
  aws-sdk
  bootstrap-sass
  cancancan (~> 1.9)
  capistrano
  capistrano-bundler
  capistrano-rails
  capistrano-rvm
  capistrano3-puma
  carrierwave
  chronic
  ckeditor!
  coffee-rails (~> 4.0.0)
  devise
  fog
  gon
  gretel (= 3.0.8)
  highcharts-rails (~> 3.0.0)
  jbuilder (~> 2.0)
  jquery-easing-rails
  jquery-rails
  jquery-slimscroll-rails
  jquery-ui-rails
  jspdf-rails
  mandrill_mailer
  mediaelement_rails
  mini_magick
  omniauth
  omniauth-facebook
  omniauth-twitter
  paperclip
  pg
  pg_search (= 0.7.8)
  pry-rails (= 0.3.2)
  puma
  quiet_assets
  rails (= 4.1.7)
  rails-jquery-autocomplete
  rails_admin
  sass-rails (~> 4.0.3)
  sdoc (~> 0.4.0)
  simple_form
  spring
  sprockets-rails
  turbolinks
  uglifier (>= 1.3.0)
  wicked_pdf
  will_paginate-bootstrap
  wkhtmltopdf-binary

BUNDLED WITH
   1.11.2

```

**Comment by renz45** [comment] 2016-05-25 14:40
It sort of looks like bundle install didn't get run on the server before assets were precompiled. Either that or something like the gemset is off. Sometimes you see these types of errors which indicate an old bundler version, but if it works in dev and not in a production environment its likely something with the environment. Bundler/rails/ruby versions look fine, so I'd check the server and maybe even run `bundle install` manually after checking that the rvm gemset is correct. Then trying running `RAILS_ENV=production bin/rake assets:precompile` manually and see if the same error persists.

**Comment by lvalenzuela** [comment] 2016-05-25 19:53
It's strange, because it works OK when I remove the gem of the gemfile.

**Comment by olivierlacan** [comment] 2016-05-26 14:08
Hey @lvalenzuela. Look at your stacktrace in your original post: 

```
ArgumentError: wrong number of arguments (0 for 1)
/home/<user>/.rvm/gems/ruby-2.1.4/gems/activejob-0/lib/active_job/queue_name.rb:6:in `queue_as'
```

**Comment by renz45** [comment] 2016-05-26 14:11
Ahh nice catch, I should looked closer down the stack trace. I'm not sure how the queue is being used, but I bet if you use a custom job instead of the quick helper it will likely work. I haven't done anything with this gem to make it work inherently with the new active job stuff.

**Comment by lvalenzuela** [comment] 2016-05-26 14:57
Hi, thanks for your help, but I'm still not able to make it work.

As I see it, everything should work with the following settings

```MandrillMailer.configure do |config|
  config.api_key = ENV['MANDRILL_API_KEY']
  config.deliver_later_queue_name = :default
end```

For some reason `config.deliver_later_queue_name = :default` is not being initialized and it crashes when the queue is used in `mandrill_template_later.rb`

Any clues on how can I fix it?

Thanks in advance

**Comment by renz45** [comment] 2016-05-26 15:08
Is this project public? I'm pretty swamped right now and don't have a ton of time to try to reproduce this. :( If the app you're talking about is public i can take a look, or if you wanted to provide a sample app that replicates the issue I can also take a look at that.

**Comment by lvalenzuela** [comment] 2016-05-26 22:40
Finally it worked downgrading the gem to version 1.0.1

I don't really know what was happening but it seems it has to do with my implementation rather than the gem itself. 

Thanks for all the help, if I manage to discover what was happening I'll let you know.

**Comment by renz45** [comment] 2016-05-27 15:17
I was thinking about this more last night, I noticed that you're using a really old version of activejob. Might it be possible to upgrade that to one of the newer versions to see if that fixes it? I'm thinking that maybe the early versions don't accept a block for queue_as here: https://github.com/renz45/mandrill_mailer/blob/master/lib/mandrill_mailer/mandrill_message_later.rb#L4

**Comment by renz45** [comment] 2016-06-16 14:16
Closing this since no one else has come across this yet.

**Closed** 2016-06-16 14:16 UTC
